{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "judy.fullname" . }}-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "judy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: judy-council
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.allowedClientNamespace | quote }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.networkPolicy.allowedClientPodLabel | quote }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}
